[language-server.typescript-language-server]
command         = "typescript-language-server"
args            = ["--stdio"]
config.hostInfo = "helix"

[language-server.typescript-language-server.config.javascript.inlayHints]
includeInlayEnumMemberValueHints                      = true
includeInlayFunctionLikeReturnTypeHints               = true
includeInlayFunctionParameterTypeHints                = true
includeInlayParameterNameHints                        = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints              = true
includeInlayVariableTypeHints                         = true


[[language]]
name                 = "javascript"
scope                = "source.js"
injection-regex      = "(js|javascript)"
language-id          = "javascript"
file-types           = ["js", "mjs", "cjs", "rules", "es6", "pac", { glob = ".node_repl_history" }, { glob = "jakefile" }]
shebangs             = ["node"]
roots                = [ "package.json" ]
comment-token        = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers     = [ "typescript-language-server" ]
indent               = { tab-width = 2, unit = "  " }
