#!/bin/sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# ----------------
# Global settings
# ----------------

yabai -m config external_bar                off:33:0\
                \
                window_placement            second_child\
                window_shadow               float\
                window_animation_duration   0.0\
                window_animation_easing     ease_in_expo\
                window_opacity              off\
                active_window_opacity       1.0\
                normal_window_opacity       0.9\
                insert_feedback_color       0xff61afef\
                \
                split_ratio                 0.50\
                auto_balance                off\
                focus_follows_mouse         off\
                \
                mouse_modifier              fn\
                mouse_action1               move\
                mouse_action2               resize\
                mouse_drop_action           swap\
                mouse_follows_focus         off\

yabai -m config layout                      bsp

yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   10


# ------------------
# Space definitions
# ------------------

yabai -m space 1 --label social
yabai -m space 2 --label mail
yabai -m space 3 --label docs
yabai -m space 4 --label browsers


# ------
# Rules
# ------

yabai -m rule --add app="^(System Settings|Clock|Calculator|Software Update|Time Machine|System Information|Finder)$" manage=off
yabai -m rule --add app="^Raycast$" title="^Settings$" manage=off
yabai -m rule --add app="^(DeepL|Ryujinx)$" manage=off

yabai -m rule --add app="^WhatsApp$" space=social
yabai -m rule --add app="^Telegram$" space=social
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Notion$" space=docs
yabai -m rule --add app="^Firefox$" space=browsers

# grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
yabai -m rule --add app="^Spotify$" scratchpad=spotify grid=11:11:1:1:9:9
yabai -m rule --add app="^Ghostty$" scratchpad=terminal grid=100:100:1:1:98:98

# Apply rules to existing windows
yabai -m rule --apply


# --------
# Signals
# --------

# Add signal to make yabai focus the other window when I close one
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"

# Signal for the raycast yabai extension
yabai -m signal --add event=space_changed action="nohup open -g raycast://extensions/krzysztoff1/yabai/screens-menu-bar?launchType=background > /dev/null 2>&1 &"

# Ghostty signals
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

echo "Yabai configuration loaded…"
