#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ---------------
# Global settings
# ---------------
yabai -m config external_bar                off:33:0\
                \
                window_placement            second_child\
                window_shadow               float\
                window_animation_duration   0.0\
                window_animation_easing     ease_in_expo\
                window_opacity              off\
                active_window_opacity       1.0\
                normal_window_opacity       0.9\
                insert_feedback_color       0xff61afef\
                \
                split_ratio                 0.50\
                auto_balance                off\
                focus_follows_mouse         autofocus\
                \
                mouse_modifier              fn\
                mouse_action1               move\
                mouse_action2               resize\
                mouse_drop_action           swap\
                mouse_follows_focus         off\

yabai -m config layout                      bsp

yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   10

# -----
# Rules
# -----
yabai -m rule --add app="^(System Settings|Clock|Calculator|Software Update|Time Machine|System Information|Finder)$" manage=off
yabai -m rule --add label="Raycast" app="^Raycast$" title="^Settings$" manage=off

# ------
# Signal
# ------
# Add signal to make yabai focus the other window when I close one
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"